### ISSUE TITLE
Song info showing "- URY" when no songs are being played

### ISSUE THREAD

**Issue by Brookke** [UniversityRadioYork/node-timelord#35]

**Comment by Brookke** [comment]
I am unsure whether "  - URY" is always returned or if " - URY" is sometimes returned

**Comment by ChrisTheBaron** [comment]
Ah. I copied and pasted from the `status-json.xsl` file, but yeah that might not _always_ be what it is.

**Comment by ChrisTheBaron** [comment]
So _currently_ it is `  - URY`, but I was tired when I did it, so chances are I'm wrong :smile:

**Comment by AJDurant** [comment]
the real fix is for icecast to be able to receive empty data to clear the
track info

**Comment by LordAro** [comment]
Closed by #36 ... hopefully
