### ISSUE TITLE
"Phantom" brackets when on mobile 

### ISSUE THREAD

**Issue by ChrisTheBaron** [UniversityRadioYork/node-timelord#37]
![Screenshot_20161029-231444.png](http://i.imgur.com/SIWwxgu.png)

**Comment by LordAro** [comment]
Text shadow broken?

**Comment by mstratford** [comment]
Can't replicate this myself...

**Comment by LordAro** [comment]
Neither can I - @ChrisTheBaron you still seeing this? Possible browser bug?

**Comment by mstratford** [comment]
@ChrisTheBaron bump :P

**Comment by LordAro** [comment]
No one's ever been able to reproduce the bug except on Chris' phone (I did
see it myself) - blame browser bug?

**Comment by ChrisTheBaron** [comment]
Yeah I'm not seeing it any more, probably a bug in Chrome.
